# roles/registry/tasks/main.yml
# This is the main task file for the registry role.
---
- include_tasks: registry.yml
  when: registry_setup

- include_tasks: mirror.yml
  when: mirror_registry_setup
