#### letsencrypt vars ####
# acme_sh_uninstall: true
acme_sh_copy_certs_to_path: "/etc/ssl/acme.sh"
acme_sh_domains: 
  - domains: ["registry.tirro.ir"]
    install_cert_reloadcmd: "docker restart registry"

#### registry vars ####
# Host paths
registry_storage_path: /var/registry/data
registry_config_base_path: /opt/registry
registry_config_file: "{{ registry_config_base_path }}/config.yml"
registry_tls_path: "{{ registry_config_base_path }}/tls"
registry_tls_src: "{{ acme_sh_copy_certs_to_path }}/{{ registry_domain }}"
registry_tls_remote_src: true
registry_auth_path: "{{ registry_config_base_path }}/auth"
registry_auth_file: "{{ registry_auth_path }}/htpasswd"

# Registry settings
registry_domain: registry.tirro.ir
registry_outbound_proxy: "http://172.17.0.1:10809"

# User credentials (override these securely with Ansible Vault)
registry_user: "ci-user"
registry_password: "CHANGEME"

