#### letsencrypt vars ####
# acme_sh_uninstall: true
acme_sh_copy_certs_to_path: "/etc/ssl/acme.sh"
acme_sh_domains: 
  - domains: ["registry.tirro.ir"]
    install_cert_reloadcmd: "docker restart registry"
