#### letsencrypt vars ####
letsencrypt_certs:
  - domain: "registry.tirro.ir"
    base_domain: "tirro.ir"
    email: "admin@tirro.ir" # It's good practice to use a real email

#### registry vars ####
# Host paths
registry_storage_path: /var/registry/data
registry_config_base_path: /opt/registry
registry_config_file: "{{ registry_config_base_path }}/config.yml"
registry_tls_path: "{{ registry_config_base_path }}/tls"
registry_auth_path: "{{ registry_config_base_path }}/auth"
registry_auth_file: "{{ registry_auth_path }}/htpasswd"

# Registry settings
registry_domain: registry.tirro.ir
registry_outbound_proxy: "http://your-outbound-proxy.com:8080"

# User credentials (override these securely with Ansible Vault)
registry_user: "ci-user"
registry_password: "CHANGEME"

