# roles/registry/tasks/main.yml
# This is the main task file for the registry role.
---
- name: Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - docker.io
      - apache2-utils # for htpasswd
    state: present
    update_cache: yes
  become: yes

- name: Ensure host directories for registry exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ registry_storage_path }}"
    - "{{ registry_config_base_path }}"
    - "{{ registry_tls_path }}"
    - "{{ registry_auth_path }}"
  become: yes
  become_user: root

- name: Template the registry config.yml
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ registry_config_file }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  notify: Restart registry container # This handler will restart the container if the config changes

- name: Create htpasswd file and add registry user
  community.general.htpasswd:
    path: "{{ registry_auth_file }}"
    name: "{{ registry_user }}"
    password: "{{ registry_password }}" # NOTE: Store this password securely in Ansible Vault
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Copy TLS certificate and key
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  loop:
    - { src: "{{ registry_tls_cert_src }}", dest: "{{ registry_tls_path }}/fullchain.pem" }
    - { src: "{{ registry_tls_key_src }}", dest: "{{ registry_tls_path }}/privkey.pem" }
  notify: Restart registry container # Also restart if certs change

- name: Deploy the Docker Registry container
  community.docker.docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    ports:
      - "5000:5000"
    env:
      HTTP_PROXY: "{{ registry_outbound_proxy }}"
      HTTPS_PROXY: "{{ registry_outbound_proxy }}"
    volumes:
      - "{{ registry_storage_path }}:/var/lib/registry"
      - "{{ registry_config_file }}:/etc/docker/registry/config.yml:ro"
      - "{{ registry_tls_path }}:/etc/docker/registry/tls:ro"
      - "{{ registry_auth_path }}:/etc/docker/registry/auth:ro"
