# roles/registry/defaults/main.yml
# Default variables for the registry role.
# You can override these in your inventory (e.g., group_vars/all/main.yml)
# roles/registry/defaults/main.yml
---
# Host paths
registry_storage_path: /var/registry/data
registry_config_base_path: /opt/registry
registry_config_file: "{{ registry_config_base_path }}/config.yml"
registry_tls_path: "{{ registry_config_base_path }}/tls"
registry_auth_path: "{{ registry_config_base_path }}/auth"
registry_auth_file: "{{ registry_auth_path }}/htpasswd"

# Registry settings
registry_domain: registry.tirro.ir
registry_outbound_proxy: "http://your-outbound-proxy.com:8080"

# User credentials (override these securely with Ansible Vault)
registry_user: "ci-user"
registry_password: "CHANGEME"

# Source paths for TLS files on your Ansible control node
# You should point these to where your certs are stored locally.
# NOTE: These variables are required if registry.domain value doesn't exist on {{ letsencrypt_certs }} list.
# registry_tls_cert_src: "/path/on/ansible/controller/to/fullchain.pem"
# registry_tls_key_src: "/path/on/ansible/controller/to/privkey.pem"
